FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

# Installation de Cypress et des dépendances
RUN npm install --save-dev cypress
RUN npx cypress install

COPY . .

# Ne pas build en production pour les tests
ENV NODE_ENV=test