global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'postgres'
    metrics_path: /metrics  
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node'  
    static_configs:
      - targets: ['node-exporter:9100']