name: CI Pipeline

on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: MedPilot_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd backend && npm install

      - name: Run tests
        run: cd backend && npm test
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: 123456
          DB_NAME: MedPilot_test
          NODE_ENV: test
          JWT_SECRET: test-secret


  e2e-tests:
    runs-on: ubuntu-latest
    name: E2E Tests

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: MedPilot_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Start Backend
        run: |
          cd backend
          npm install
          npm start &
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: 123456
          DB_NAME: MedPilot_test
          NODE_ENV: test

      - name: Start Frontend
        run: |
          cd frontend
          npm install
          npm run build
          npm start &
        env:
          NEXT_PUBLIC_API_URL: http://localhost:4000

      - name: Wait for services
        run: |
          npx wait-on http://localhost:3000 --timeout 60000
          npx wait-on http://localhost:4000 --timeout 60000

      - name: Run E2E Tests
        run: |
          cd frontend
          npm run test:e2e