name: CI Pipeline

on:
  push:
    branches: [main, develop, 'feature/**']
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ESLint Backend
        run: cd backend && npm install && npm run lint
      - name: ESLint Frontend
        run: cd frontend && npm install && npm run lint


  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Backend Unit Tests
        run: |
          cd backend
          npm install
          npm test -- --coverage

      - name: Frontend Unit Tests
        run: |
          cd frontend  
          npm install
          npm test -- --coverage


  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Images
        run: docker-compose build